version: 0.2

# See https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

phases:
  pre_build:
    commands:
      - echo "pre_build phase started at $(date)"
      - cd ${CODEBUILD_SRC_DIR_source2}
      # See https://github.com/it-vegard/a11y-reference-website
      - npm install -g node-gyp
  build:
    # Primary source dir   : $CODEBUILD_SRC_DIR
    # Secondary source dir : $CODEBUILD_SRC_DIR_source2
    commands:
      - echo "build phase started at $(date)"
      - cd ${CODEBUILD_SRC_DIR_source2}
      - npm install
  post_build:
    commands:
      - echo "post_build phase started at $(date)"
      - cd ${CODEBUILD_SRC_DIR_source2}
      - npm run test
      - echo "================================================="
      - pwd
      - echo "================================================="
      - find . -maxdepth 2 -type d -ls
      - echo "================================================="
      - ls -l
      - echo "================================================="
      # See https://playwright.dev/
      # - npx playwright install chrome
      # - npm run test:chrome

reports:
  test-report:
    base-directory: $CODEBUILD_SRC_DIR_source2
    files:
      - "results.xml"
    file-format: "JUNITXML"
